config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: %i[create update destroy]
    resources :likes, only: %i[create destroy]
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root 'posts#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :name, presence: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :category
  belongs_to :creator, class_name: 'User'

  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, class_name: 'PostLike', dependent: :destroy

  validates :title, :body, presence: true
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  has_ancestry

  belongs_to :user, class_name: 'User'
  belongs_to :post, counter_cache: :comments_count

  validates :content, presence: true, length: { maximum: 1000 }
end

app/models/post_like.rb
# frozen_string_literal: true

class PostLike < ApplicationRecord
  belongs_to :user
  belongs_to :post, counter_cache: :likes_count

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :posts, inverse_of: :creator, dependent: :destroy
  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, class_name: 'PostLike', dependent: :destroy

  validates :username,
            presence: true,
            length: { minimum: 4, maximum: 20 },
            format: { with: /\A[a-zA-Z0-9_]+\z/ }

  def username
    read_attribute(:username).presence || email.split('@').first
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_comment, only: %i[update destroy]
  before_action :authenticate_user!
  before_action :allow_only_author, only: %i[update destroy]

  # POST /comments
  def create
    @comment = current_user.comments.new(comment_params.merge(post_id: params.expect(:post_id)))

    if @comment.save
      redirect_to @comment.post, notice: t('.created', resource: @comment.model_name.human)
    else
      redirect_to @comment.post, status: :unprocessable_content, alert: t('comments.error')
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to @comment.post, notice: t('.updated', resource: @comment.model_name.human), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy!

    redirect_to @comment.post, notice: t('.destroyed', resource: @comment.model_name.human), status: :see_other
  end

  private

  def allow_only_author
    redirect_to(root_path, status: :forbidden) unless @comment.user == current_user
  end

  def set_comment
    @comment = PostComment.find(params.expect(:id))
  end

  def comment_params
    params.expect(post_comment: %i[content ancestry])
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :set_post, only: %i[destroy create]
  before_action :set_like, only: %i[destroy]

  before_action :authenticate_user!

  def create
    @post.likes.create(user_id: current_user.id)

    redirect_to @post
  end

  def destroy
    @like.destroy

    redirect_to @like.post
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_like
    @like = current_user.likes.find_by(id: params[:id])

    redirect_to(@post) unless @like
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :allow_only_author, only: %i[edit update destroy]

  # GET /posts
  def index
    @posts = Post.order(created_at: :desc)
  end

  # GET /posts/1
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to @post, notice: t('.created', resource: @post.model_name.human)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: t('.updated', resource: @post.model_name.human), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy!

    redirect_to posts_path, notice: t('.destroyed', resource: @post.model_name.human), status: :see_other
  end

  private

  def allow_only_author
    redirect_to(root_path, status: :forbidden) unless @post.creator == current_user
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.expect(post: %i[title body category_id])
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def updated?(resource)
    resource.updated_at != resource.created_at
  end
end

app/views/comments/_comment.html.slim
div id="#{dom_id comment}"

.card.pe-0.mt-3
  .card-header.d-flex.justify-content-between
    = comment.user.username
    em = render 'shared/timestamps', resource: comment

  .card-body.pe-0.pb-0
    .p.card-text.mb-3 = comment.content

    - if current_user
      .d-flex.justify-content-between
        button.btn.btn-sm.btn-outline-primary.my-2[
          type='button'
          data-bs-toggle='collapse'
          data-bs-target="#reply-form-#{comment.id}"
          aria-expanded='false'
          aria-controls="reply-form-#{comment.id}"
        ] = t('.reply')
        - if current_user == comment.user
            = button_to t('.delete'), post_comment_path(@post, comment),
              method: :delete, class: 'btn btn-danger mt-1 me-1'
      .collapse id="reply-form-#{comment.id}"
        = render 'comments/form', comment: comment.children.build(post: comment.post)

    - comment.children.each do |child_comment|
      = render 'comments/comment', comment: child_comment

app/views/comments/_form.html.slim
= simple_form_for(comment, url: post_comments_path(comment.post_id)) do |form|
  .form-inputs
    = form.hidden_field :ancestry, value: comment.ancestry

    = form.input :content, label_html: { style: 'display: none' }

  .form-actions
    = form.submit t('.create'), class: 'btn btn-primary'

app/views/layouts/_header.html.slim
header
  nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
    .container-fluid
      .navbar-brand.me-auto = link_to(t('navigation.home'), root_path, class: 'link-info text-decoration-none')

      ul.navbar-nav.mb-2.mb-md-0
        - if user_signed_in?
          li.nav-item.m-2.text-white-50 = t('navigation.signed_in_as', username: current_user.username)
          li.nav-item.me-2 = button_to t('navigation.logout'), destroy_user_session_path,
            method: :delete, class: 'btn btn-danger'
        - else
          li.nav-item.me-2 = link_to t('navigation.sign_up'), new_user_registration_path, class: 'btn btn-primary'
          li.nav-item.me-2 = link_to t('navigation.sign_in'), new_user_session_path, class: 'btn btn-primary'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = content_for(:title) || t('navigation.html_title')
    meta[name='viewport' content='width=device-width,initial-scale=1']
    meta[name='apple-mobile-web-app-capable' content='yes']
    meta[name='mobile-web-app-capable' content='yes']
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    / Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!)
    / = tag.link rel: 'manifest', href: pwa_manifest_path(format: :json)
    link[rel='icon' href='/icon.png' type='image/png']
    link[rel='icon' href='/icon.svg' type='image/svg+xml']
    link[rel='apple-touch-icon' href='/icon.png']
    / Includes all stylesheet files in app/assets/stylesheets
    = stylesheet_link_tag :app, 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
    - # rubocop:disable Rails/OutputSafety
    = Sentry.get_trace_propagation_meta.html_safe
    - # rubocop:enable Rails/OutputSafety
  body
    .pb-4 = render 'layouts/header'
    = yield

app/views/posts/_form.html.slim
= simple_form_for(post) do |form|
  .form-inputs
    = form.input :category_id, collection: Category.all, required: true

    = form.input :title, autofocus: true

    = form.input :body

  .form-actions.d-grid.mt-4
    = form.submit class: 'btn btn-primary btn-lg'

app/views/posts/_post.html.slim
.card.my-3 id='#{dom_id post}'
  .card-body
    h3 = link_to post.title, post

    p = post.body.truncate(200)

    em
      = t('posts.show.by_user_at', username: post.creator.username)
      = render 'shared/timestamps', resource: post

    br
    = "#{t('posts.show.comments_count', count: post.comments.size)} | "
    = t('posts.show.people_liked', count: post.likes.size)

app/views/posts/edit.html.slim
.container.mt-5
  .row.justify-content-center
    .col-md-6.col-lg-6
      h1 = t('.title')

      == render 'form', post: @post

      br

      div
        => link_to t('.show'), @post
        '|
        =< link_to t('.index'), posts_path

app/views/posts/index.html.slim
.container.mt-5
  = render 'shared/alerts'

  .d-flex.justify-content-between.align-items-center
    h2 = t('.title')
    = link_to t('.new'), new_post_path, class: 'btn btn-outline-primary'

  #posts
    - @posts.each do |post|
      == render post

app/views/posts/new.html.slim
.container.mt-5
  .row.justify-content-center
    .col-md-6.col-lg-6
      h1 = t('.title')

      == render 'form', post: @post

      br

      div
        = link_to t('.index'), posts_path

app/views/posts/show.html.slim
.container.mt-5
  .row.justify-content-center
    ol.breadcrumb
      .breadcrumb-item = link_to t('.index'), posts_path
      .breadcrumb-item = @post.category.name

    = render 'shared/alerts'

    h2 = @post.title

    p = @post.body

    .d-flex.justify-content-between
      em.me-auto
        = t('.by_user_at', username: @post.creator.username)
        = render 'shared/timestamps', resource: @post

      - if (like = @post.likes.find_by(user: current_user))
        = button_to post_like_path(@post, like), class: 'btn btn-link p-0 text-danger', method: :delete do
          i.bi.bi-heart-fill
      - else
        = button_to post_likes_path(@post), class: 'btn btn-link p-0 text-muted' do
          i.bi.bi-heart

      .ms-2
        = t('posts.show.people_liked', count: @post.likes.size)

    - if current_user == @post.creator
      .d-flex.justify-content-end
        = link_to t('.edit'), edit_post_path(@post), class: 'btn btn-primary me-2'
        = button_to t('.delete'), @post, method: :delete, class: 'btn btn-danger'

    hr.my-4

    h3
      = t('posts.show.comments_count', count: @post.comments.size)

    - if current_user
      = render 'comments/form', comment: @post.comments.build

    .pb-5
      - @post.comments.order(created_at: :desc).where(ancestry: '/').each do |comment|
        = render 'comments/comment', comment: comment

app/views/shared/_alerts.html.slim
- if notice
  .alert.alert-success = notice
- if alert
  .alert.alert-danger = alert

app/views/shared/_timestamps.html.slim
span data-controller='local-time'
  time data-local-time-target='time' data-datetime='#{resource.created_at.iso8601}'
    = resource.created_at
  - if updated?(resource)
    = t('.last_updated_at')
    time data-local-time-target='time' data-datetime='#{resource.updated_at.iso8601}'
      = resource.updated_at

app/views/users/shared/_error_messages.html.slim
- if resource.errors.any?
  #error_explanation[data-turbo-cache='false']
    h2
      = I18n.t('errors.messages.not_saved',
        count: resource.errors.count,
        resource: resource.class.model_name.human.downcase)
    ul
      - resource.errors.full_messages.each do |message|
        li
          = message

app/views/users/shared/_links.html.slim
.mt-4.d-flex.align-items-center.justify-content-between
  - if controller_name != 'sessions'
    = link_to new_session_path(resource_name), class: 'text-decoration-none mb-2' do
      = t('devise.sessions.new.title')

  - if devise_mapping.registerable? && controller_name != 'registrations'
    = link_to new_registration_path(resource_name), class: 'text-decoration-none mb-2' do
      = t('devise.registrations.new.title')